### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by RubenKelevra** [joonty/systemd_mon#7]
```
Mär 09 10:55:47 gna.vfn-nrw.de systemd[1]: systemd_mon.service: Failed with result 'exit-code'.
Mär 09 10:55:47 gna.vfn-nrw.de audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd_mon comm="systemd" exe="/usr/lib/systemd/systemd" 
Mär 09 10:55:47 gna.vfn-nrw.de systemd[1]: systemd_mon.service: Unit entered failed state.
Mär 09 10:55:47 gna.vfn-nrw.de systemd[1]: systemd_mon.service: Main process exited, code=exited, status=1/FAILURE
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from <internal:abrt_prelude>:2:in `<compiled>'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems.rb:187:in `try_activate'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems/specification.rb:936:in `find_inactive_by_path'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems/specification.rb:748:in `stubs'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems/specification.rb:870:in `dirs'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems.rb:355:in `path'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems.rb:332:in `paths'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems.rb:332:in `new'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: from /usr/share/rubygems/rubygems/path_support.rb:34:in `initialize'
Mär 09 10:55:47 gna.vfn-nrw.de systemd_mon[14715]: /usr/share/rubygems/rubygems/path_support.rb:71:in `path=': undefined method `+' for nil:NilClass (NoMethodError)
Mär 09 10:55:47 gna.vfn-nrw.de systemd[1]: Starting SystemdMon...

```

**Comment by breezzz** [comment]
with new ruby (2.4) this problem is solved.
